INSERT INTO `produits` (`nom`, `description`, `prix`, `image_url`) VALUES
('Chemise en lin beige', 'Chemise légère en lin, coupe droite, idéale pour la saison chaude.', 45000.00, 'https://picsum.photos/seed/hbe-produit-1/600/600'),
('Robe fluide imprimée', 'Robe fluide à motifs colorés, tissu doux et respirant.', 62000.00, 'https://picsum.photos/seed/hbe-produit-2/600/600'),
('Baskets urbaines noires', 'Baskets confortables au design urbain, semelle antidérapante.', 78000.00, 'https://picsum.photos/seed/hbe-produit-3/600/600'),
('Sac à main en cuir', 'Sac à main en cuir véritable, plusieurs compartiments.', 95000.00, 'https://picsum.photos/seed/hbe-produit-4/600/600'),
('Jean slim bleu délavé', 'Jean coupe slim, tissu extensible pour plus de confort.', 52000.00, 'https://picsum.photos/seed/hbe-produit-5/600/600'),
('Veste en jean oversize', 'Veste en jean coupe oversize, look intemporel.', 68000.00, 'https://picsum.photos/seed/hbe-produit-6/600/600'),
('T-shirt col rond blanc', 'T-shirt basique en coton, coupe régulière, indispensable du dressing.', 25000.00, 'https://picsum.photos/seed/hbe-produit-7/600/600'),
('Montre classique cuir', 'Montre au bracelet en cuir, cadran sobre et élégant.', 88000.00, 'https://picsum.photos/seed/hbe-produit-8/600/600'),
('Lunettes de soleil rétro', 'Lunettes de soleil monture ronde, protection UV400.', 32000.00, 'https://picsum.photos/seed/hbe-produit-9/600/600'),
('Casquette brodée', 'Casquette ajustable avec broderie discrète.', 18000.00, 'https://picsum.photos/seed/hbe-produit-10/600/600'),
('Pull en maille torsadée', 'Pull chaud en maille torsadée, parfait pour la saison fraîche.', 58000.00, 'https://picsum.photos/seed/hbe-produit-11/600/600'),
('Ceinture en cuir marron', 'Ceinture en cuir véritable, boucle métallique classique.', 27000.00, 'https://picsum.photos/seed/hbe-produit-12/600/600'),
('Sandales en cuir', 'Sandales confortables en cuir souple, semelle ergonomique.', 41000.00, 'https://picsum.photos/seed/hbe-produit-13/600/600'),
('Foulard en soie imprimé', 'Foulard léger en soie, motifs colorés, plusieurs façons de le porter.', 30000.00, 'https://picsum.photos/seed/hbe-produit-14/600/600'),
('Blazer ajusté noir', 'Blazer coupe ajustée, idéal pour les tenues chics.', 105000.00, 'https://picsum.photos/seed/hbe-produit-15/600/600'),
('Short en toile beige', 'Short décontracté en toile résistante, coupe droite.', 34000.00, 'https://picsum.photos/seed/hbe-produit-16/600/600'),
('Bracelet perles artisanal', 'Bracelet fait main avec perles colorées, pièce unique.', 15000.00, 'https://picsum.photos/seed/hbe-produit-17/600/600'),
('Chaussures de ville en cuir', 'Chaussures habillées en cuir, finitions soignées.', 92000.00, 'https://picsum.photos/seed/hbe-produit-18/600/600'),
('Sac à dos toile robuste', 'Sac à dos spacieux en toile résistante, plusieurs poches.', 54000.00, 'https://picsum.photos/seed/hbe-produit-19/600/600'),
('Écharpe en laine grise', 'Écharpe douillette en laine, parfaite pour l''hiver.', 22000.00, 'https://picsum.photos/seed/hbe-produit-20/600/600');
